### PR TITLE
Fixing #2433, disabling Synesthesia 3 Suits with 1x One of Each

### PR DESCRIPTION
**Pull request by N1trate**
The script now keeps saying
```
Missing variant: Synesthesia & Black (3 Suits)
Missing variant: Synesthesia & Dark Rainbow (3 Suits)
Missing variant: Synesthesia & Gray (3 Suits)
Missing variant: Synesthesia & Dark Brown (3 Suits)
Missing variant: Synesthesia & Dark Null (3 Suits)
```
But since that's what we wanted, I guess it isn't too bad?
I'm assuming you need to manually force it to got through with the missing variants and clean the database if there was ever a game of those variants.

### CODE REVIEW

**Comment by Zamiell** [comment]
yes, i'll need to delete those games manually, can you tell me the variant ids of those 5 variants

**Comment by N1trate** [comment]
I'll go with those numbers, from the current variants.txt.
```
Synesthesia & Black (3 Suits) (#1646)
Synesthesia & Dark Rainbow (3 Suits) (#1808)
Synesthesia & Gray (3 Suits) (#1812)
Synesthesia & Dark Brown (3 Suits) (#1816)
Synesthesia & Dark Null (3 Suits) (#1820)
```

**Comment by DrAnax** [comment]
https://hanab.live/api/v1/variants

**Comment by Zamiell** [comment]
nitrate, please include the updated variants.json in your pr

**Comment by N1trate** [comment]
Do you also want the variants.txt, or only the variants.json?

**Comment by Zamiell** [comment]
i forgot about the variants.txt
yes, your pr should include both so that all i have to do is accept the pr and restart the server

**Comment by N1trate** [comment]
I'm assuming you already purged the database of those games if there are. I disabled the check for "Missing variants" to generate the files.

**Comment by Zamiell** [comment]
> I'm assuming you already purged the database of those games if there are.

I haven't purged the database yet, I will do that after the server is restarted, in case e.g. someone decided to create a game of those variants like right now

> I disabled the check for "Missing variants" to generate the files.

sounds good

**Comment by Zamiell** [comment]
for reference:

hanabi=> delete from games where variant_id=1646;
DELETE 77
hanabi=> delete from games where variant_id=1808;
DELETE 0
hanabi=> delete from games where variant_id=1812;
DELETE 0
hanabi=> delete from games where variant_id=1816;
DELETE 1
hanabi=> delete from games where variant_id=1820;
DELETE 0
hanabi=>

**Pull request merged**
