### PR TITLE
Fix for num_games < 1000

### LINKED ISSUE #2425: double click vtk doesn't work for players with <1000 games

### PR DESCRIPTION
**Pull request by DrAnax**
Closes #2425

### CODE REVIEW

**Comment by DrAnax** [comment]
Linter message cryptic

No issues shown on VSC
Console ./client/lint_client.sh only shows the same warning
image

**Comment by Zamiell** [comment]
delete node_modules + package-lock.json
then run npm ci
then the lint script will work correctly, assuming you are on a modern version of node (16+)

**Comment by Zamiell** [comment]
specifically, the linter is telling you to open the "drawUI.ts" file in vscode and press ctrl+s to save it (which will run prettier)

**Comment by DrAnax** [comment]
> delete node_modules + package-lock.json then run npm ci

npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.

**Comment by Zamiell** [comment]
sorry, don't delete package-lock.json, only delete node_modules

**Comment by DrAnax** [comment]
running npm i now...

**Comment by DrAnax** [comment]
./lint_client.sh 
Checking formatting...
[warn] src/game/ui/drawUI.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?

Same result. VSC doesn't show any underlined orange errors; ctrl+S didn't do a thing

**Comment by Zamiell** [comment]
you probably need to rebase your fork on master that has the new vscode files

**Comment by Zamiell** [comment]
for reference look at this:
https://github.com/Hanabi-Live/hanabi-live/blob/main/.vscode/settings.json#L47-L48

these setting make it so that it runs prettier on save

**Comment by DrAnax** [comment]
> these settings make it so that it runs prettier on save

Nada. VSC does nothing on save. Furthermore it doesn't show lint errors anymore. Ctrl+Shift+P did fix the document though (semicolon missing)

Any idea what's changed?

(I made sure Prettier - Code formatter is installed)

**Comment by Zamiell** [comment]
make sure that you don't have personal settings that are in conflict, because those will override workspace settings

also make sure you close and reopen vscode

**Pull request merged**
