### PR TITLE
RGB mix

### PR DESCRIPTION
**Pull request by vEnhance**
last random variant for a while i think :P

from https://github.com/Hanabi-Live/hanabi-live/issues/2381#issuecomment-1312813183

### CODE REVIEW

**Comment by Zamiell** [comment]
can you split the formatting changes into a separate pr

**Comment by Zamiell** [comment]
how about i merge this in march

**Comment by vEnhance** [comment]
> how about i merge this in march

sounds good

**Comment by Zamiell** [comment]
can you rebase this so that the phantom changes go away

**Comment by vEnhance** [comment]
ok done

**Comment by vEnhance** [comment]
> how about i merge this in march

hi 👋

**Pull request merged**
