### PR TITLE
Positive color clues

### PR DESCRIPTION
**Pull request by DrAnax**
Closes: #1039

### CODE REVIEW

**Comment by DarthGandalf** [comment]
3 clues were given; the cards turned into known 1s after the second color clue, but the 3rd clue didn't update the pip

image

**Comment by DrAnax** [comment]
I tried altering the border, but it didn't always look right (or wasn't visible enough). Here's the dinal render in various resolutions:

image

image

image

**Comment by DarthGandalf** [comment]
a more subtle one:

изображение
изображение

**Comment by DrAnax** [comment]
> a more subtle one:

Try it also in smaller resolutions

**Comment by DarthGandalf** [comment]
изображение
изображение
изображение

**Comment by DarthGandalf** [comment]
here's with border instead:

изображение
изображение

but it's barely visible on white background

**Comment by DrAnax** [comment]
> here's with border instead:
> but it's barely visible on white background

And if you try it in smaller resolution it's next to invisible.

**Comment by DrAnax** [comment]
There, either solution with a circle works, it's a matter of preference now.

**Comment by DarthGandalf** [comment]
here's code for the subtle highlight I posted above:

```js
  if (highLight === true) {
    ctx.save();
    ctx.beginPath();
    ctx.arc(3, 5, 130, 0, 360);
    ctx.closePath();
    const gradient = ctx.createRadialGradient(0,0,3, 0,0,130);
    gradient.addColorStop(0, 'rgba(238, 188, 29, 0.7)');
    gradient.addColorStop(0.4, 'rgba(238, 188, 29, 0.5)');
    gradient.addColorStop(0.7, 'rgba(238, 188, 29, 0.2)');
    gradient.addColorStop(1, 'rgba(238, 188, 29, 0.0)');
    ctx.fillStyle = gradient;
    ctx.shadowColor = "rgba(0, 0, 0, 0)";
    ctx.fill();
    ctx.restore();
  }
```

**Comment by nitawa-hl** [comment]
I tried something! I think it looks quite good, except that the pips/shadows are doing weird things, and that the blue pip overlaps with the 1, but just to give you an idea before I spend any more time on it...

image
image
image

**Comment by nitawa-hl** [comment]
The issue with the yellow pip comes from the shapeFunction, see here: https://jsbin.com/katofenapi/edit?js,output

**Comment by Zamiell** [comment]
ok so which is one is the best one out of all the ones that people posted

**Comment by DrAnax** [comment]
> ok so which is one is the best one out of all the ones that people posted

We have rested our case, it's up to you to decide.

**Comment by Zamiell** [comment]
which one do you like

**Comment by DarthGandalf** [comment]
Let's do this:

who wants the [full circle behind](https://user-images.githubusercontent.com/325092/153515324-ba58cb55-5b6e-43e1-994d-50e0c8fc08b0.png), react with Rocket
who wants [gradient circle behind](https://user-images.githubusercontent.com/325092/153522987-193de8f5-ca8c-4ee6-82de-3efd7dd5dcbd.png), react with Heart
who wants the [border](https://user-images.githubusercontent.com/83447589/153680192-d45f01a9-5301-4709-8fb9-af874649844f.png), react with Eyes

**Comment by DrAnax** [comment]
I'm not a good candidate to ask because of my poor eyesight (a lot of presbyopia). Plus I would be biased towards what I did.

**Comment by Romain672** [comment]
Since it's close, I would not said no to a screenshot with thrice the same hand. And then for differents variants (synesthesia & X-Ones?).

**Comment by DarthGandalf** [comment]
@Zamiell looks like the border got 1 more vote than circle, so let's merge #2607

**Pull request merged**
