### PR TITLE
Table spectators, owners and beautiful eyes

### LINKED ISSUE #1253: Spectate a pre-game
Often I want to chat in a pregame lobby without fear that the game would start suddenly. Currently the solution is to /msg people who are in it, which is not ideal

### LINKED ISSUE #2605: [suggestion]: When table owner leaves, pass the ownership to the next player.
Currently, when the owner leaves / disconnects, the table is destroyed. I suggest keeping the table (if there are still players in) and pass the ownership to the next player.

### PR DESCRIPTION
**Pull request by DrAnax**
Closes #1253 
Addresses #2553 
Closes #2605 

- Fixed asking for cursor image each time (svg in css file)
- Replaced creepy eye cursor with beloved googly eyes
- In lobby: click the spectators column on a pregame to join as a spectator
- In pregame: notifications when players join game or spectators join table
- In pregame: when table owner leaves, ownership is passed on to the next of kin

### CODE REVIEW

**Comment by Zamiell** [comment]
what does it look like now

**Comment by DrAnax** [comment]
image

image

image
(table = spectator, game = player)

Owner left
image

Outside world
image

Can't screenshot the cursor, imagine the googly eyes (indicating a spectator during game) as cursor. This appears only when hovering the spectators cell.

Icons:
image

The "forbidden entry" properly appears when the table is full.

**Comment by Zamiell** [comment]
I kind of like the googly eyes over the spectacles, the spectacles seem kind of boring

**Comment by rogers-j** [comment]
Maybe instead of `joined the table` just `is spectating`?

**Comment by DarthGandalf** [comment]
>  (table = spectator, game = player)

The mere fact that you needed to explain it here means that the wording in the UI is unclear

I agree with "is spectating" or such

**Pull request merged**
