### PR TITLE
Update spinner to reflect the updated cards

### PR DESCRIPTION
**Pull request by calvinballing**
Updates the spinner to use the Hanab blue-card symbol instead of the older diamond symbol.  Also changes the rotation style to be more three dimensional, and displays the back of the card when facing away.

New:
ajax
 
Old:
ajax-old

### CODE REVIEW

**Comment by Zamiell** [comment]
neat

**Comment by Zamiell** [comment]
nice work

**Comment by Zamiell** [comment]
can you just get rid of the unused ajax image.
we dont need to keep unused images in there, we can always get the old version of the file from git

**Comment by Zamiell** [comment]
also are you on discord?

**Comment by calvinballing** [comment]
> can you just get rid of the unused ajax image. we dont need to keep unused images in there, we can always get the old version of the file from git if we need it

I've removed the old one in this update.  I just joined the Discord, and I'm Jim#4145.

**Review by DrAnax — APPROVED** [review]

**Comment by Zamiell** [comment]
Ok, thanks. I was just curious if u had another ID, since I didn't recognize your name

**Pull request merged**
