### PR TITLE
New Variant: Funnels

### PR DESCRIPTION
**Pull request by DrAnax**
Props to @jack67889

Referenced in #2027

### CODE REVIEW

**Comment by DrAnax** [comment]
Chimneys is also ready, awaiting for the PR to be accepted, to avoid conflict in variant IDs

**Comment by Zamiell** [comment]
i dont want to implement more than one trial variant at a time

**Comment by DrAnax** [comment]
> i dont want to implement more than one trial variant at a time

There's no variant on trial unless a server restart

**Comment by Zamiell** [comment]
this pr has branch conflicts now

**Pull request closed without merging**
