### PR TITLE
Require a strict majority (>50%) for VTK

### LINKED ISSUE #2765: Vote to kill in 2p should require both players to vote
Currently in 2p, just one player voting to kill is enough to end the game. It would be more useful if it required both players to vote, since they can always double click to terminate if they want to kill dictatorially anyway. Related #2414

### PR DESCRIPTION
**Pull request by timotree3**
Necessary vote counts to kill after this change:
- 2/2 (unchanged since #2769 made it 2/2)
- 2/3 (unchanged)
- 3/4 (used to be 2/4; improvement IMO)
- 3/5 (unchanged)
- 4/6 (used to be 3/6; 4/6 seems slightly more intuitive to me, but it's unclear if it's better)

### CODE REVIEW

**Comment by Zamiell** [comment]
we want 4-player and 6-player to be unchanged

**Comment by Zamiell** [comment]
also this pr has branch conflicts

**Comment by timotree3** [comment]
This PR is specifically for 4 and 6-player. #2769 was for the 2p only case. I edited the top comment accordingly.

I believe this is a good change and a [community poll](https://discord.com/channels/140016142600241152/140016142600241152/1055303846890573954
) agrees: image

**Comment by Zamiell** [comment]
i prefer if 4 player requires 2 votes

in my mind, requiring half of the players to continue to play when they do not want to play seems really wrong

**Comment by Zamiell** [comment]
closing this for now

**Pull request closed without merging**
