### PR TITLE
Update repo

### PR DESCRIPTION
**Pull request by DrAnax**

### CODE REVIEW

**Comment by DrAnax** [comment]
Can actions somehow check which part of the code the PR changes and only run those specific tests?

**Comment by Zamiell** [comment]
i believe so

**Comment by Zamiell** [comment]
you'll have to do more research into that, i'm not a github actions expert

**Comment by DrAnax** [comment]
> you'll have to do more research into that, i'm not a github actions expert

https://stackoverflow.com/a/63822945/180243

**Comment by DrAnax** [comment]
Also: https://github.com/tj-actions/changed-files

**Comment by Zamiell** [comment]
ah good, that seems simple enough

**Comment by Zamiell** [comment]
submit a PR that adds those fields to the ci.yml file for client and server respectively

**Pull request merged**
