### PR TITLE
Efficiency in /missing-scores and /shared-missing-scores

### LINKED ISSUE #2086: include in /missing the required efficiency and color code (yellow/red) for the variants
Issue opened by Discord user: Zamiel#8743

### PR DESCRIPTION
**Pull request by DrAnax**
Closes #2086 

image

### CODE REVIEW

**Comment by DrAnax** [comment]
That was such a cute innocent request :[

**Comment by DrAnax** [comment]
Fixing bugs, do not accept yet

**Comment by DrAnax** [comment]
Thanks @N1trate for all your help

**Comment by Zamiell** [comment]
nice work

**Pull request merged**
