### PR TITLE
Support seeds with "legacy-x-" in front

### PR DESCRIPTION
**Pull request by DrAnax**

### CODE REVIEW

**Comment by Zamiell** [comment]
what is the point of the len check

**Comment by DrAnax** [comment]
Can't people put their own seed? This breaks if the seed is just `legacy-`

**Comment by Zamiell** [comment]
ok this is a little confusing, but the user inputted seed is a suffix to the actual seed

meaning that it would be p2v5sLOLDICKS

**Comment by DrAnax** [comment]
What if at some point we decide to rename again the seeds? I thought this would be a good safeguard

**Comment by Zamiell** [comment]
well if we renamed the seeds we still wouldn't allow arbitrary prefixes

**Pull request merged**
