### PR TITLE
Join a game as hydra head from lobby

### LINKED ISSUE #2567: Join a game as hydra head
When playing as hydra, a player needs to join as spectator as some other player, but without seeing that player's hand before switching view to that player's view. This is very hard to do without accidentally seeing the hand.

UI may look like this:
Выделение_408

### PR DESCRIPTION
**Pull request by Krycke**
Closes #2567

### CODE REVIEW

**Comment by Zamiell** [comment]
how does it work

**Comment by Krycke** [comment]
The players names in lobby is clickable if you are not a player in the
game. If you do click on one of the names, you will enter the game as a
spectator shadowing that player.

The mouse cursor is a detective emoji when hovering over a players name,
and the name it self becomes blue.

Den fre 9 dec. 2022 13:17James ***@***.***> skrev:

**Comment by Zamiell** [comment]
it doesn't seem to work

**Comment by Zamiell** [comment]
looks like your CSS has an error:

```
Fatal error: undefined:1:111489: property missing ':'
```

**Comment by Krycke** [comment]
Did you solve it? Seams to work live now.

**Comment by Zamiell** [comment]
no, thats an error from the critical build script

can you submit a pr that makes the critical build script work properly

**Comment by Krycke** [comment]
Which one is the critical build script? 
Everything works fine on my workspace, and I can see the change live on https://hanab.live/lobby

Do you have any more information on the problem?

**Pull request merged**
