### PR TITLE
holiday mix

### PR DESCRIPTION
**Pull request by vEnhance**
- Fix path in update_variant_files.sh
- Holiday mix
- Valentine mix

### CODE REVIEW

**Comment by Zamiell** [comment]
should we save these variants for when the actual respective holidays arrive?

**Comment by vEnhance** [comment]
I don't mind either way.

**Comment by Zamiell** [comment]
ok, do you want to split out the bugfix part of the PR for now?

**Comment by vEnhance** [comment]
OK split off in #2702

**Comment by vEnhance** [comment]
> should we save these variants for when the actual respective holidays arrive?

@Zamiell there seems to be a bit of interest in Holiday Mix competition in the Hanabi Central server
Maybe we can merge this in a week-ish so people have time to practice and play the comp seeds over late Nov / early December?

**Comment by Zamiell** [comment]
ok

**Comment by Zamiell** [comment]
do you want to get rid of the valentine mix from the pr then

**Comment by vEnhance** [comment]
> do you want to get rid of the valentine mix from the pr then

I could but I think it's more trouble than it's worth since variant ID conflicts could potentially arise between now and February

**Comment by Zamiell** [comment]
I feel like we should probably wait until February to add the valentine's variant though right?

**Comment by vEnhance** [comment]
I guess so
I'll just revert the Feb thing and reapply it on a later patch, it's only a couple lines

**Comment by vEnhance** [comment]
Ready to merge whenever then I'll poke libster about making comp happen

**Comment by Zamiell** [comment]
how about we merge it on dec 1

**Comment by vEnhance** [comment]
sure, close enough

**Comment by vEnhance** [comment]
> how about we merge it on dec 1

happy december :)

**Comment by Zamiell** [comment]
its live now, thanks!

**Comment by shemetz** [comment]
Why is this new variant called "Holiday Mix" when, as far as I can tell, it's just Christmas colors?

image

**Comment by Zamiell** [comment]
what do you want to call it

**Comment by shemetz** [comment]
Christmas Mix

**Pull request merged**
