### PR TITLE
Put connect messages in a go routine

### PR DESCRIPTION
**Pull request by Krycke**
Made the friendsHistoryID little sharper and put connecting Messages in a separate go routine to not hinder other connecting users if one is slow

### CODE REVIEW

**Comment by Zamiell** [comment]
can you describe the db changes in more detail

**Comment by Krycke** [comment]
The sql in only stripping the two joins, as we are only interested in the games.id, which we already have in the participation table. The query itself is actually not changed.

**Comment by Zamiell** [comment]
ok thanks

**Comment by Zamiell** [comment]
future steps:

can we do a PR to lazily give friend data when they click on the friend history button?

future questions:

the above won't solve the root of the problem because as long as the DB query takes longer than 30 seconds the server will "deadlock", so are future DB call optimizations needed?

**Comment by Krycke** [comment]
Agree, right now the query reads all database rows and go through them to find the ones that are played by friends, after that it does the same thing again to find the ones played by you, then take the diff of those. When all that is done we sort the set, and return only 10 rows. What we can do is having an index on when a table is created, and only go through the lines from games played the last week, or month or something. That will make this alot quicker.

But that said, by putting this on a separate go routine it shouldn't deadlock.

**Pull request merged**
