### PR TITLE
Adds Opposites Mix

### PR DESCRIPTION
**Pull request by David707x**
modified:   misc/variants.txt
modified:   packages/data/src/createVariantsJSON/getVariantDescriptions.ts
modified:   packages/data/src/json/variants.json

### CODE REVIEW

**Comment by Zamiell** [comment]
ok, lets merge this in February, since the variants for December will be Sudoku, and the variants for January will be the new dark ones

**Comment by Zamiell** [comment]
also this PR doesn't pass CI, make sure that your pull requests pass CI before submitting

**Comment by David707x** [comment]
Tbh I'm not sure why it's failing CI or how to make it pass since it is effectively a 4 line change

**Comment by Zamiell** [comment]
you can click on the red x to see why its failing, or run lint.sh locally

**Pull request closed without merging**
