### PR TITLE
Hard variant -> 1.33

### PR DESCRIPTION
**Pull request by vEnhance**
Implements https://github.com/hanabi/hanabi.github.io/issues/1036

### CODE REVIEW

**Comment by Zamiell** [comment]
can we define this as a constant somewhere instead of making the change multiple times

**Comment by vEnhance** [comment]
Sure, where do you want to put it?

**Comment by Zamiell** [comment]
some constants.ts file

**Comment by vEnhance** [comment]
OK I put it in `client/src/constants.ts`

**Comment by Zamiell** [comment]
good thanks

**Pull request merged**
