### PR TITLE
Save spectator notes

### PR DESCRIPTION
**Pull request by Krycke**
Saving spectatornotes even if they change table.
Visually differenciate them from players notes.
Don't save spectators notes in the database.

### CODE REVIEW

**Review by Krycke — COMMENTED** [review]
Fixing the lint problem

**Comment by Krycke** [comment]
SpecNotes

**Comment by Zamiell** [comment]
can you get rid of the extra whitespace on the top? it looks a little buggy

**Comment by Krycke** [comment]
SpecNotes

**Comment by Zamiell** [comment]
looks good thanks

**Comment by Zamiell** [comment]
can you rebase this on main? if you look at the "files changed" tab on github, it has a fuckton of changes that are not related to this PR

**Comment by Krycke** [comment]
True. I'll fix that tomorrow

**Comment by Zamiell** [comment]
for now i wanna let the current code sit for a few days, remind me in a few days and ill restart the server with this

**Comment by Zamiell** [comment]
and thanks for the pr!

**Pull request merged**
