### PR TITLE
Add Sudoku variant

### PR DESCRIPTION
**Pull request by kesslermaximilian**
This implements #2115 and is based on newdukes work at #2114. The first commit here is just a rebased version of newdukes commit from some 2 years ago.

Some details on the features:
- UI shows the starting value of each stack once it is determined (either when a card has been played or if it is the last remaining stack without a card played)
- UI shows number of cards played for each stack, since one loses track of the individual progress quite quick in this variant
- Empathy (for trash) and maximum score calculation adjusted to Sudoku variants

Some implementational details:
- Server games now have an attribute 'playStackStarts' which stores the starting values of each stack. It is only used in Sudoku variants (otherwise it is never read)
- Server also has corresponding implementation to calculate maximum scores in Sudoku variant
- Added some helper methods in `misc.go` to compute minima and check arrays for contained elements
- Client also has new `playStackStarts` attribute in the `GameState`, analog to Server
- Client UI has a second row of LabelTexts below stacks that are only created in Sudoku variants (to write the number of played cards in there)
    - Creation of this row is toggled by the new `showStackStarts` attribute in the `variants.json` file

In case you would like more documentation in the code, I could add more detailed documentation to the changes.

### CODE REVIEW

**Comment by Zamiell** [comment]
Make sure it passes ci

**Comment by kesslermaximilian** [comment]
Yes, I'm on it currently. Somehow the linters do not work properly for me locally

**Comment by kesslermaximilian** [comment]
Passing now

**Comment by Zamiell** [comment]
did you test the new ui elements in keldon mode

**Comment by kesslermaximilian** [comment]
Oh no, totally not, I forgot that existed. Will do

**Comment by kesslermaximilian** [comment]
Works

**Comment by kesslermaximilian** [comment]
Ah no, when it reaches your turn, it overlaps a little, let me see what we can do there

**Comment by Zamiell** [comment]
i dont think we have room for a new ui element, is there some other solution we can do

**Comment by kesslermaximilian** [comment]
An alternative would be to put the second line in the Hover above the Stacks. But I sort of don't like this, because in contrast to how suits behave, that information changes all the time, so you would like to see it.

**Comment by kesslermaximilian** [comment]
I'm very much a fan of these, at least in Non-Keldon mode. As a compromise, we could put them in the Hover in Keldon mode and leave them as implemented right now otherwise.

**Comment by Zamiell** [comment]
ok

**Comment by kesslermaximilian** [comment]
One suggestion we had from Tony was the following: Say the stack starts at 2 and 234 have been played already. Then we could put <bold>234</bold>51 under the stack. This fits in one row and shows all the information needed. Even has the additional upside that you can see the last card of each suit etc. What do you think of that?

**Comment by Zamiell** [comment]
seems fine

**Comment by kesslermaximilian** [comment]
As I see it, the Konva.text does not support different font styles within the same text element. Do you know how to implement above approach? I forgot to mention that the idea in the above example would be to have 234 in bold and 51 not in bold, to also see how many cards have been played.
But in case we can't do the boldface properly, I think I will go with the hover solution in Keldon mode

**Comment by Zamiell** [comment]
no idea, you could just make two different text elements

**Comment by Zamiell** [comment]
konva sucks its ancient technology

**Comment by kesslermaximilian** [comment]
> no idea, you could just make two different text elements

Problem with two different elements is that it's hard to align then: Since the number of boldface characters is varying, we would either dynamically need to change sizes of these fields (and calculate these so that in total, stuff is centered), or have two at the same position and somehow align text inside these properly). I don't feel comfortable getting this to work in a consistent way (bold font is probably bigger etc), so in case there is no easier way, I will not implement it like that.

In case someone has further suggestions, I'm open for them, but probably it'll be the hover solution in Keldon.

**Comment by kesslermaximilian** [comment]
> konva sucks its ancient technology

Yeah I see

**Comment by Zamiell** [comment]
go is pretty good, it has some downsides, but nowadays i prefer typescript because of all of the tooling involved (prettier+eslint is amazing, as well as package managers, monorepo tools, etc.)

**Comment by kesslermaximilian** [comment]
UI is now also done for Keldon mode (only >2 players, since in 2p, there was still space) and shown in the Hover there. Any more things that came to your mind before we can merge this?

**Pull request merged**
