### PR TITLE
New Variant: Funnels

### PR DESCRIPTION
**Pull request by DrAnax**
Props to @jack67889

Referenced in #2027

### CODE REVIEW

**Comment by Zamiell** [comment]
lets wait a few weeks before merging so that people have time to play odds & evens

**Comment by Zamiell** [comment]
branch has conflicts, if you fix it i will merge

**Comment by Zamiell** [comment]
@vEnhance do you wanna fix the conflicts

**Comment by vEnhance** [comment]
> @vEnhance do you wanna fix the conflicts

Fixed conflicts in #2675

**Comment by jack67889** [comment]
In #2532 @DrAnax mentioned he also had the Chimney variant (that's the opposite of Funnel) of #2027 ready. Not sure if that pull request is somewhere or is it lost?

**Comment by vEnhance** [comment]
> In #2532 @DrAnax mentioned he also had the Chimney variant (that's the opposite of Funnel) of #2027 ready. Not sure if that pull request is somewhere or is it lost?

Mentioned in https://github.com/Hanabi-Live/hanabi-live/pull/2532#issuecomment-1024450162 but I don't know if that PR ever got submitted

**Pull request closed without merging**
