### PR TITLE
Draw deceptive 1s, 5s

### PR DESCRIPTION
**Pull request by DarthGandalf**
hanabi-decep
hanabi-decep-5
hanabi-decep-cb
hanabi-decep-cb5
hanabi-decep-style
hanabi-decep-style5

### CODE REVIEW

**Comment by Zamiell** [comment]
neat
i like it

**Comment by Zamiell** [comment]
now fix your vscode so that you dont push code violating the linter to github

**Comment by DarthGandalf** [comment]
I don't even use vscode

And that's why there is a CI

**Comment by Zamiell** [comment]
what do you use, vim?

**Comment by Zamiell** [comment]
> And that's why there is a CI

it spams my inbox if you keep pushing commits for useless linting fixes, so i would appreciate you getting it right before you push

**Comment by DarthGandalf** [comment]
Yes, vim. I haven't configured automatic linter for js

**Comment by Zamiell** [comment]
vim can lint in the same way vscode can AFAIK

**Pull request merged**
