### PR TITLE
Fixes drag problems in hypo

### LINKED ISSUE #2389: when in hypo, cards can have wrong orientation
steps to reproduce:

1) turn on keldon mode
2) start a hypothetical on the turn of someone with cards that do not have a horizontal orientation
3) click and release a card

normally, this would reorient the card back to normal, but since the X/Y positions didn't change, no tween applies

### PR DESCRIPTION
**Pull request by Krycke**
Closes #2389

### CODE REVIEW

**Comment by Zamiell** [comment]
oh, this makes hypos too hard to use unfortunately

**Comment by Zamiell** [comment]
its very difficult to drag rotated cards to where they need to go

**Comment by Krycke** [comment]
Hm... This also fixes the bug with shadows not getting removed when your not in keldon mode. Maybe we should add a keldon check around it. And just keep it for the few that uses keldon mode?

**Comment by Zamiell** [comment]
i guess?

**Pull request merged**
